--[[
    Game name fixes for better HLTB matching.
    Maps Steam game names to HLTB-compatible names.
]]

return {
    ["Legacy of Kain Soul Reaver 1&2 Remastered"] = "Legacy of Kain: Soul Reaver 1 & 2 Remastered",
    ["LEGO Star Wars - The Complete Saga"] = "LEGO Star Wars: The Complete Saga",
    ["LEGO Star Wars III - The Clone Wars"] = "LEGO Star Wars III: The Clone Wars",
    ["Rock of Ages 2: Bigger & Boulder"] = "Rock of Ages II: Bigger & Boulder",
    ["FINAL FANTASY TACTICS - The Ivalice Chronicles"] = "Final Fantasy Tactics: The Ivalice Chronicles",
    ["Lobotomy Corporation | Monster Management Simulation"] = "Lobotomy Corporation",
    ["Huntsman: The Orphanage (Halloween Edition)"] = "Huntsman: The Orphanage",
    ["Divinity: Original Sin (Classic)"] = "Divinity: Original Sin",
    ["Grand Theft Auto V Legacy"] = "Grand Theft Auto V",
    ["Kao the Kangaroo: Round 2 (2003 re-release)"] = "Kao the Kangaroo: Round 2",
    ["Machinika: Museum"] = "Machinika Museum",
    ["PICO PARK:Classic Edition"] = "PICO PARK: Classic Edition",
    ["SEGA Mega Drive and Genesis Classics"] = "SEGA Genesis Classics Collection",
    ["Space Pilgrim Episode II: Epsilon Indi"] = "Space Pilgrim: Episode Two - Epsilon Indi",
    ["Ace of Spades: Battle Builder"] = "Ace of Spades",
    ["ATOM RPG: Post-apocalyptic indie game"] = "ATOM RPG",
    ["Dark Messiah of Might & Magic"] = "Dark Messiah of Might and Magic",
    ["Disco Elysium - The Final Cut"] = "Disco Elysium",
    ["Heroes of Might & Magic III - HD Edition"] = "Heroes of Might and Magic III",
    ["Life Goes On: Done to Death"] = "Life Goes On",
    ["Meadow - A Shelter Game"] = "Meadow",
    ["Warhammer 40,000: Dawn of War II: Retribution"] = "Warhammer 40,000: Dawn of War II - Retribution",
    ["STAR WARS Battlefront II (Classic, 2005)"] = "STAR WARS Battlefront II",
    ["Marvel’s Spider-Man Remastered"] = "Marvel's Spider-Man Remastered",
    ["Disco Elysium - The Final Cut"] = "Disco Elysium",
    ["Lewd Girls, Leave Me Alone! I Just Want to Play Video Games and Watch Anime! ~ Hentai Edition"] = "Lewd Girls, Leave Me Alone! I Just Want to Play Video Games and Watch Anime! Hentai Edition",
    ["PICO PARK:Classic Edition"] = "PICO PARK: Classic Edition",
    ["Ranch Simulator: Build, Hunt, Farm"] = "Ranch Simulator",
    ["Sea of Thieves: 2025 Edition"] = "Sea of Thieves",
    ["Stardew Valley"] = "Stardew Valley",
    ["Baldur's Gate 3"] = "Baldur's Gate 3",
    ["Vampire Survivors"] = "Vampire Survivors",
    ["The Deed: Dynasty"] = "The Deed: Dynasty",
    ["Borderlands 2 RU"] = "Borderlands 2",
    ["Dead Rising 3 Apocalypse Edition"] = "Dead Rising 3",
    ["Dying Light 2 Stay Human: Reloaded Edition"] = "Dying Light 2 Stay Human",
    ["HELLDIVERS Dive Harder Edition"] = "Helldivers",
    ["Heroes of Might & Magic V"] = "Heroes of Might and Magic V",
    ["Heroes of Might & Magic V: Hammers of Fate"] = "Heroes of Might and Magic V: Hammers of Fate",
    ["Heroes of Might & Magic V: Tribes of the East"] = "Heroes of Might and Magic V: Tribes of the East",
    ["Might & Magic X - Legacy"] = "Might and Magic X: Legacy",
}
