--[[
    Game name fixes for better HLTB matching.
    Maps Steam game names to HLTB-compatible names.
]]

return {
    ["Ace of Spades: Battle Builder"] = "Ace of Spades",
    ["ATOM RPG: Post-apocalyptic indie game"] = "ATOM RPG",
    ["Batman: Arkham Asylum Game of the Year Edition"] = "Batman: Arkham Asylum GOTY",
    ["Borderlands 2 RU"] = "Borderlands 2",
    ["Borderlands Game of the Year Enhanced"] = "Borderlands: Game of the Year",
    ["Borderlands GOTY Enhanced"] = "Borderlands: Game of the Year",
    ["Dark Messiah of Might & Magic"] = "Dark Messiah of Might and Magic",
    ["Dead Rising 3 Apocalypse Edition"] = "Dead Rising 3",
    ["Disco Elysium - The Final Cut"] = "Disco Elysium",
    ["Divinity: Original Sin (Classic)"] = "Divinity: Original Sin",
    ["Double Dragon: Neon"] = "Double Dragon Neon",
    ["Dying Light 2 Stay Human: Reloaded Edition"] = "Dying Light 2 Stay Human",
    ["FINAL FANTASY TACTICS - The Ivalice Chronicles"] = "Final Fantasy Tactics: The Ivalice Chronicles",
    ["Grand Theft Auto V Legacy"] = "Grand Theft Auto V",
    ["HELLDIVERS Dive Harder Edition"] = "Helldivers",
    ["Heroes of Might & Magic III - HD Edition"] = "Heroes of Might and Magic III",
    ["Heroes of Might & Magic V"] = "Heroes of Might and Magic V",
    ["Heroes of Might & Magic V: Hammers of Fate"] = "Heroes of Might and Magic V: Hammers of Fate",
    ["Heroes of Might & Magic V: Tribes of the East"] = "Heroes of Might and Magic V: Tribes of the East",
    ["Huntsman: The Orphanage (Halloween Edition)"] = "Huntsman: The Orphanage",
    ["Kao the Kangaroo: Round 2 (2003 re-release)"] = "Kao the Kangaroo: Round 2",
    ["KILL la KILL -IF"] = "Kill la Kill The Game: IF",
    ["Legacy of Kain Soul Reaver 1&2 Remastered"] = "Legacy of Kain: Soul Reaver 1 & 2 Remastered",
    ["LEGO Star Wars - The Complete Saga"] = "LEGO Star Wars: The Complete Saga",
    ["LEGO Star Wars III - The Clone Wars"] = "LEGO Star Wars III: The Clone Wars",
    ["Leisure Suit Larry 1 - In the Land of the Lounge Lizards"] = "Leisure Suit Larry in the Land of the Lounge Lizards",
    ["Leisure Suit Larry 2 - Looking For Love (In Several Wrong Places)"] = "Leisure Suit Larry Goes Looking for Love (in Several Wrong Places)",
    ["Leisure Suit Larry 3 - Passionate Patti in Pursuit of the Pulsating Pectorals"] = "Leisure Suit Larry III: Passionate Patti in Pursuit of the Pulsating Pectorals",
    ["Leisure Suit Larry 5 - Passionate Patti Does a Little Undercover Work"] = "Leisure Suit Larry 5: Passionate Patti Does a Little Undercover Work",
    ["Leisure Suit Larry 6 - Shape Up Or Slip Out"] = "Leisure Suit Larry 6: Shape Up or Slip Out!",
    ["Lewd Girls, Leave Me Alone! I Just Want to Play Video Games and Watch Anime! ~ Hentai Edition"] = "Lewd Girls, Leave Me Alone! I Just Want to Play Video Games and Watch Anime! Hentai Edition",
    ["Life Goes On: Done to Death"] = "Life Goes On",
    ["Lobotomy Corporation | Monster Management Simulation"] = "Lobotomy Corporation",
    ["Machinika: Museum"] = "Machinika Museum",
    ["Marvel’s Spider-Man Remastered"] = "Marvel's Spider-Man Remastered",
    ["Meadow - A Shelter Game"] = "Meadow",
    ["Might & Magic X - Legacy"] = "Might and Magic X: Legacy",
    ["PICO PARK:Classic Edition"] = "PICO PARK: Classic Edition",
    ["Plants vs. Zombies GOTY Edition"] = "Plants vs. Zombies",
    ["Ranch Simulator: Build, Hunt, Farm"] = "Ranch Simulator",
    ["Rock of Ages 2: Bigger & Boulder"] = "Rock of Ages II: Bigger & Boulder",
    ["Sea of Thieves: 2025 Edition"] = "Sea of Thieves",
    ["SEGA Mega Drive and Genesis Classics"] = "SEGA Genesis Classics Collection",
    ["Sid Meier's Civilization® VI"] = "Sid Meiers Civilization VI",
    ["SimCity™ 4 Deluxe Edition"] = "SimCity 4 Deluxe",
    ["Space Pilgrim Episode II: Epsilon Indi"] = "Space Pilgrim: Episode Two - Epsilon Indi",
    ["STAR WARS Battlefront II (Classic, 2005)"] = "STAR WARS Battlefront II",
    ["ToeJam & Earl: Back in the Groove!"] = "ToeJam & Earl: Back in the Groove",
    ["Total War: NAPOLEON – Definitive Edition"] = "Napoleon: Total War",
    ["Warhammer 40,000: Dawn of War II: Retribution"] = "Warhammer 40,000: Dawn of War II - Retribution",
    ["We Love Katamari REROLL+ Royal Reverie"] = "We Love Katamari Reroll + Royal Reverie",
}
